# frozen_string_literal: true

source "https://rubygems.org"

gem 'rspec'
gem 'rubocop', require: false
gem 'rubocop-factory_bot', require: false
gem 'rubocop-md', require: false
gem 'rubocop-migration', require: false
gem 'rubocop-performance', require: false
gem 'rubocop-rails', require: false
gem 'rubocop-rspec', require: false
gem 'rubocop-thread_safety', require: false
